file=open("30 days 30 hour operations.txt","w")
file.write('I have completed 10 days successfully ')
file.close()
file=open("30 days 30 hour operations.txt","a")
n=input("Enter your name:")
file.write(n)
print("The name was  appended successfully")
file.close()
