print('30 days 30 hours challenge');
print("30 days 30 hours challenge");
Hours='thirty';
print(Hours);
Days='Thirty days';
print(Days[0]);
Challenge = "I will win";
print(Challenge[7:10]);
print(len(Challenge));
print(Challenge.lower());
a = "30 Days";
b = "30 hours";
c = a + b;
print(c);
c = a + " " + b;
print(c);
text = "Thirty days and Thirty hours";
x = text.casefold();
print(x);
text1="DON’T TROUBLE TROUBLE UNTIL TROUBLE TROUBLES YOU";
y = text.capitalize();
print(y);
z = text.find('days');
print(z);
text2='rex';
x1 = text2.isalpha();
print(x1);
text3='rex123';
y1 = text3.isalnum();
print(y1);
